### ISSUE TITLE
Improve project description

### ISSUE THREAD

**Issue by ocram** [delight-im/HTML-Sheets-of-Paper#1]
- may be useful for providing invoices, legal notices, etc.
- similar to the foundation of a word document
- like the sheets in Google Docs
- no skeuomorphic paper

**Comment by barbalex** [comment]
a quick example how to implement this would be nice

**Comment by barbalex** [comment]
in which browsers does this work?

**Comment by ocram** [comment]
@barbalex Thanks for your questions!

Implementing this is really easy and notes on how to do this have been added here:
https://github.com/delight-im/HTML-Sheets-of-Paper/commit/5e7c6c422e3e7732f3dee5046d9078f8573436cc

A basic browser compatibility list has been added as well:https://github.com/delight-im/HTML-Sheets-of-Paper/commit/65f11278467c4b05c12f231e113ef5890417c163

This might require some more tests, though, and thus may be amended or modified in the future. Help is appreciated, of course :)

**Comment by ocram** [comment]
Project description improved in https://github.com/delight-im/HTML-Sheets-of-Paper/commit/ebbe5e84cc925c248a4031b9a2e8e2a7be1359d7

**Comment by barbalex** [comment]
thanks!
