### ISSUE TITLE
Is the developer available for questions?

### ISSUE THREAD

**Issue by ghxstweb** [delight-im/HTML-Sheets-of-Paper#20]
I've been using this repo extensively and am running into some issues with line numbering and formatting with this particular system. is the developer available to discuss some of the aspects of the page breaking system so that I can potentially fix it?

**Comment by ocram** [comment]
Sure, the public bug tracker and community support is right here, and paid support is available via email. You can find the address on the page of the organization of this repository. Otherwise, feel free to post and discuss your issues here publicly.

**Comment by ghxstweb** [comment]
Thanks @ocram! I wanted to ask how the print/media feature works, because what shows up during the print/savetoPDF feature is NOT the same as what is rendered on the browser. Would you be able to help me figure out how to get the exact render of what I see on the browser to the printToPDF features?

**Comment by ocram** [comment]
Sure, if you have specific issues or bugs you found, it’s probably best to create an issue here, and otherwise feel free to send an email.
