### ISSUE TITLE
look great but...

### ISSUE THREAD

**Issue by hstorc** [delight-im/HTML-Sheets-of-Paper#4]
I am looking for a solution similar as yours.
However I didn't see any solve for display a very long table and making sure the page breaks 
accordingly to the size of the 'page' size.
Example - put the attached table> and you'll see there is incorrect paging.

**Comment by ocram** [comment]
Thanks, I think this is tracked [here](https://github.com/delight-im/HTML-Sheets-of-Paper/issues/2) already.
